import pytest
from src.agents.shared_state import get_combined_data
from src.agents.analyst.tools import run_pandas_query
from unittest.mock import patch

def test_pipeline_data_to_analyst(mock_excel_file):
    """Verify that analyst can query the actual DataFrame generated by DataLoader."""
    with patch('pathlib.Path.exists', return_value=True):
        # 1. Pipeline start: shared_state should load the mock data
        df = get_combined_data()
        assert not df.empty
        
        # 2. Pipeline continuation: run_pandas_query on the loaded data
        # Let's count metrics. We expect 'Orders', 'Gross Profit UE', 'Perfect Orders'
        result = run_pandas_query("df['METRIC'].nunique()")
        assert '3' in str(result)
        
        # 3. Complex aggregation
        # Mean Value for Polanco should be (2.5 + ... + 3.3)/9 = 2.9
        query = "df[df['METRIC'] == 'Gross Profit UE']['VALUE'].mean()"
        result = run_pandas_query(query)
        assert '2.9' in str(result)
